# MINIMAL Safe config for troubleshooting
# Absolute minimum settings to get training started

model:
  model_name: "Qwen/Qwen2-VL-2B-Instruct"
  torch_dtype_str: "bfloat16"
  trust_remote_code: True

data:
  train:
    collator_name: "vision_language_with_padding"
    datasets:
      - dataset_name: "Tushar365/disaster-assessment-qwen2vl"
        split: "train"
        dataset_kwargs:
          processor_name: "Qwen/Qwen2-VL-2B-Instruct"
          return_tensors: True

training:
  output_dir: "output/simple_test"
  trainer_type: "TRL_SFT"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  max_steps: 10  # Very short test
  learning_rate: 1e-5
  logging_steps: 2
  enable_wandb: False
